"""Generate DATA_QUALITY.md from the interim logs: every parsing failure, imputed or
derived value, restatement, ambiguous headcount and fiscal-year alignment issue.
"""
from __future__ import annotations

import json
import os
import sys
from pathlib import Path

import pandas as pd
import yaml

from config import DATA_DIR, INTERIM_DIR, RESULTS_DIR, ROOT, load_firms

DOCS_DIR = Path(os.environ.get("FTE_DOCS_DIR", ROOT))
IS_DEMO = os.environ.get("FTE_DOCS_DIR") is not None

STATIC = """
## Conventions that affect every comparison

- **Fiscal-year label.** `fiscal_year` is the calendar year in which the fiscal year ends,
  which is also the company's own label (NVDA "fiscal 2025" ends January 2025).
  `cal_year` shifts fiscal years ending January–May back one year so that NVDA FY2025,
  CRM FY2025 and WMT FY2025 sit with calendar 2024; June–December year-ends keep their
  year (MSFT FY2024 = 2024, ACN FY2024 = 2024). All break tests and event studies use
  `cal_year`, so "FY2023" means the first fiscal year mostly inside calendar 2023.
- **Restatements.** For each period the most recently filed value is used (the basis the
  company itself now presents), so a revenue figure can differ from the 10-K originally
  filed for that year. Every case where filings disagree by more than 1% is listed below.
- **Headcount is a point-in-time count**, usually at fiscal-year end, while revenue is a
  flow over the year. Revenue/FTE therefore mixes an end-of-year denominator with a
  full-year numerator; a firm that hires late in the year looks less productive. No
  averaging is applied because most firms disclose only the year-end number.
- **Full-time vs total.** Firms disclose different things: full-time employees (most),
  full-time and part-time combined (AMZN, WMT, COST), "associates" or "people". The
  sentence is stored for every value; `includes_part_time` marks the combined cases.
  Contractors are never in the denominator and are not measurable from filings.
- **Deflation.** Real values are in 2024 dollars using the PCE price index averaged over
  each firm's fiscal window relative to the calendar-2024 average. CPI-U deflators are
  also in the panel (`deflator_cpi`).
- **Foreign private issuers** (SPOT, TSM, WIT, INFY, ARM) file 20-F under IFRS; SHOP filed
  40-F before switching to 10-K. Values are kept in reporting currency and `usd` is false
  for non-USD filers, which excludes them from every regression and index. TSM (TWD),
  WIT (INR) and SPOT (EUR) would need FRED exchange-rate series to be comparable.
- **Banks** (JPM, BAC, WFC, GS) have no cost-of-revenue or gross-profit concept.
- **Broadcom** changed CIK in its 2018 redomiciliation; pre-2018 facts live under the old
  CIK and are not merged. **GE** spun off GE HealthCare (2023) and GE Vernova (2024), so its
  series is not comparable across those years. **Atlassian** moved from 20-F to 10-K in
  FY2023. **Uber** and **DoorDash** count employees, not drivers/dashers.
- **AI-mention intensity** is measured on the whole annual report, so a firm whose risk
  factors discuss AI at length scores high without deploying anything. It is a
  heterogeneity split, not a measure of adoption.
"""


def md_table(df: pd.DataFrame, cols: list[str], max_rows: int = 60) -> str:
    if df is None or len(df) == 0:
        return "_none_\n"
    d = df[cols].head(max_rows).copy()
    for c in d.columns:
        d[c] = d[c].map(lambda v: "" if (isinstance(v, float) and pd.isna(v)) or v is None else (f"{v:,.0f}" if isinstance(v, float) and abs(v) >= 1000 else (f"{v:.3f}" if isinstance(v, float) else str(v))))
    lines = ["| " + " | ".join(cols) + " |", "|" + "---|" * len(cols)]
    for r in d.itertuples(index=False):
        lines.append("| " + " | ".join(str(x).replace("|", "/").replace("\n", " ")[:220] for x in r) + " |")
    if len(df) > max_rows:
        lines.append(f"\n_{len(df) - max_rows} more rows in the source CSV_")
    return "\n".join(lines) + "\n"


def read(name: str) -> pd.DataFrame | None:
    p = INTERIM_DIR / name
    return pd.read_csv(p) if p.exists() and p.stat().st_size > 0 else None


def main(argv=None) -> int:
    firms = load_firms()
    panel = pd.read_csv(DATA_DIR / "panel.csv") if (DATA_DIR / "panel.csv").exists() else None
    fin_log, review, filings, cik = read("financials_log.csv"), read("headcount_review.csv"), read("filings.csv"), read("cik_check.csv")
    checks = json.loads((RESULTS_DIR / "checks.json").read_text()) if (RESULTS_DIR / "checks.json").exists() else {}
    out = ["# Data quality\n"]
    if IS_DEMO:
        out.append("> **SYNTHETIC FIXTURE RUN.** Every figure referenced here was generated by `tests/make_fixtures.py`; "
                   "nothing is a real company value.\n")
    out.append("Generated by `src/write_data_quality.py` from the interim logs. Regenerate with `make quality`.\n")
    out.append(STATIC)

    out.append("\n## Coverage\n")
    if panel is not None:
        cov = panel.groupby("ticker").agg(cohort=("cohort", "first"), years=("fiscal_year", "count"),
                                          first=("fiscal_year", "min"), last=("fiscal_year", "max"),
                                          headcount_years=("headcount", lambda s: int(s.notna().sum())),
                                          currency=("currency", "first")).reset_index()
        in_panel = set(cov.ticker)
        missing = [f["ticker"] for f in firms if f["ticker"] not in in_panel]
        out.append(f"{len(cov)} of {len(firms)} sample firms in the panel, {len(panel)} firm-years, "
                   f"{int(panel.headcount.notna().sum())} with a resolved headcount.\n")
        if missing:
            out.append(f"\n**Firms with no panel rows** (fetch or parse failed, or not in this run): {', '.join(missing)}\n")
        out.append("\n" + md_table(cov, list(cov.columns), max_rows=100))
    else:
        out.append("_panel.csv not built yet_\n")

    out.append("\n## Fetch and identity failures\n")
    items = []
    if cik is not None and (~cik["match"]).any():
        items.append("CIK mismatches: " + "; ".join(f"{r.ticker} yaml={r.yaml_cik} sec={r.sec_cik}" for r in cik[~cik["match"]].itertuples()))
    if filings is not None:
        bad = filings[filings.status != "ok"]
        for r in bad.itertuples():
            items.append(f"{r.ticker} FY{r.fiscal_year} {r.form} {r.accn}: {r.status}")
    out.append(("- " + "\n- ".join(items) + "\n") if items else "_none_\n")

    out.append("\n## Headcount: unresolved, ambiguous and flagged values\n")
    if review is not None and len(review):
        out.append(f"{len(review)} filings in `data/interim/headcount_review.csv` (no candidate sentence, or competing candidates). "
                   "These firm-years have `headcount` = NA in the panel unless resolved.\n\n")
        out.append(md_table(review, ["ticker", "fiscal_year", "reason", "candidates"]))
    else:
        out.append("_no unresolved filings_\n")
    if panel is not None:
        pt = panel[panel.includes_part_time == True]
        out.append(f"\n**Values that include part-time employees** ({len(pt)} firm-years): " +
                   (", ".join(sorted(pt.ticker.unique())) if len(pt) else "none") + "\n")
        ct = panel[panel.mentions_contractors == True]
        out.append(f"\n**Filings whose employee section mentions contractors / contingent workers** ({len(ct)} firm-years): " +
                   (", ".join(sorted(ct.ticker.unique())) if len(ct) else "none") + " — contractor substitution is not measurable from filings.\n")
        dei = panel[panel.headcount_vs_dei_reldiff > 0.05]
        out.append("\n**Parsed headcount vs dei:EntityNumberOfEmployees differing by >5%**\n\n" +
                   md_table(dei, ["ticker", "fiscal_year", "headcount", "dei_employees", "headcount_vs_dei_reldiff", "headcount_sentence"]))
        llm = panel[panel.headcount_method == "llm_fallback"]
        out.append(f"\n**Values chosen by the LLM fallback**: {len(llm)}" + (" — " + ", ".join(f"{r.ticker} FY{r.fiscal_year}" for r in llm.itertuples()) if len(llm) else "") + "\n")

    out.append("\n## Financials: restatements, tag switches, derived values, missing concepts\n")
    if fin_log is not None and len(fin_log):
        rest = fin_log[fin_log.max_rel_dev > 0.01]
        out.append("**Periods where filings disagree by >1% (latest filed value used)**\n\n" +
                   md_table(rest, ["ticker", "fy_end", "concept", "tag", "val", "n_variants", "max_rel_dev", "filed"]))
        alt = fin_log[fin_log.alt_tags.fillna("").ne("")]
        out.append("\n**Periods where two candidate tags disagree by >1% (first tag in priority order used)**\n\n" +
                   md_table(alt, ["ticker", "fy_end", "concept", "tag", "val", "alt_tags"]))
        sw = fin_log.groupby(["ticker", "concept"]).tag.nunique().reset_index()
        sw = sw[sw.tag > 1]
        if len(sw):
            det = fin_log[fin_log.set_index(["ticker", "concept"]).index.isin(sw.set_index(["ticker", "concept"]).index)]
            det = det.groupby(["ticker", "concept"]).apply(lambda g: ", ".join(f"{t} ({g[g.tag == t].fy_end.min()[:4]}–{g[g.tag == t].fy_end.max()[:4]})" for t in g.tag.unique()), include_groups=False).reset_index(name="tags used")
            out.append("\n**Tag switches within a firm's series**\n\n" + md_table(det, ["ticker", "concept", "tags used"]))
    if panel is not None:
        der = panel[panel.gross_profit_tag.fillna("").str.startswith("derived")]
        out.append(f"\n**Gross profit derived as revenue − cost of revenue** (no GrossProfit tag): " +
                   (", ".join(f"{t} ({g.fiscal_year.min()}–{g.fiscal_year.max()})" for t, g in der.groupby("ticker")) if len(der) else "none") + "\n")
        concepts = ["revenue", "cost_of_revenue", "gross_profit", "operating_income", "net_income", "capex", "sbc", "rnd", "dna"]
        miss = panel.groupby("ticker")[concepts].apply(lambda g: g.isna().sum()).reset_index()
        miss = miss[(miss[concepts] > 0).any(axis=1)]
        out.append("\n**Missing concept values (count of fiscal years) — never imputed**\n\n" + md_table(miss, ["ticker"] + concepts, max_rows=100))
        fye = panel[panel.fye_month_observed != panel.fye_month_yaml].groupby("ticker").fiscal_year.apply(lambda s: ", ".join(map(str, s))).reset_index()
        out.append("\n**Fiscal-year-end month in the data differs from companies.yaml**\n\n" + md_table(fye, ["ticker", "fiscal_year"]))
        nonusd = panel[~panel.usd].groupby("ticker").currency.first().reset_index()
        out.append("\n**Non-USD filers, excluded from regressions and indices**\n\n" + md_table(nonusd, ["ticker", "currency"]))
        part = panel[panel.deflator_months < 12]
        out.append("\n**Fiscal years deflated with fewer than 12 months of price data** (latest years; FRED lags)\n\n" +
                   md_table(part, ["ticker", "fiscal_year", "fy_end", "deflator_months"]))
        noh = panel.groupby("ticker").overhire_resid_2022.first()
        noh = noh[noh.isna()].index.tolist()
        out.append(f"\n**Firms without an overhiring residual** (fewer than 4 headcount points in 2015–2019, or no FY2022): "
                   + (", ".join(noh) if noh else "none") + "\n")
        no19 = sorted(set(panel.ticker) - set(panel[(panel.cal_year == 2019) & panel.rev_per_fte_real.notna()].ticker))
        out.append(f"\n**Firms excluded from the 2019=100 indices** (no 2019 value): " + (", ".join(no19) if no19 else "none") + "\n")

    out.append("\n## Sanity checks (`make check`)\n")
    if checks:
        for b in checks.get("benchmarks", []):
            a = "n/a" if b.get("actual") is None else f"{b['actual']:,.0f}"
            out.append(f"- benchmark {b['ticker']} FY{b['fiscal_year']} {b['metric']}: actual {a}, expected ~{b['expected']:,.0f} → **{b['status']}**\n")
        for f in checks.get("failures", []):
            out.append(f"- **FAIL** {f}\n")
        for w in checks.get("warnings", []):
            out.append(f"- warn: {w}\n")
    else:
        out.append("_not run_\n")

    out.append("\n## Layoff context\n")
    lay = read("layoffs_by_firm_year.csv")
    if lay is None or len(lay) == 0:
        out.append("layoffs.fyi CSV not supplied (`data/raw/layoffs_fyi/layoffs.csv`); layoff tags in the decomposition read "
                   "'not supplied'. layoffs.fyi has no stable export URL, so this is a manual download.\n")
    else:
        out.append(f"{len(lay)} firm-years with layoffs.fyi events. Counts are as reported by the press and are incomplete by construction.\n")

    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    (DOCS_DIR / "DATA_QUALITY.md").write_text("".join(out))
    print(f"wrote {DOCS_DIR / 'DATA_QUALITY.md'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
